config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  resources :problems do
    resources :answers
  end

  # get 'knowledge_points/all_children' => 'knowledge_points#all_children'
  resources :knowledge_points do
    member do
      get :all_children
    end
  end

  resources :tags do
    member do
      get :all_children
      post :new_children
      post :create_children
    end
  end

  devise_for :users
  resources :users

  root to: 'visitors#index'
end

app/models/knowledge_point.rb
class KnowledgePoint < ApplicationRecord
  attr_accessor  :firstLevelKP, :firstLevelKPSet, :secondLevelParent, :secondLevelKPSet, :thirdLevelGrandParent, :thirdLevelParent, :thirdLevelKPSet

  # before_destroy :ensure_not_referenced_by_any_knowledge_point

  validates :name, :parent_id, :level, presence: true
  validates :name, uniqueness: true

  def self.all_children(parent_id = -1)
     KnowledgePoint.where("parent_id = ?", parent_id)
  end

  def self.latest
    KnowledgePoint.order(:updated_at).last
  end

  private

  def ensure_not_referenced_by_any_knowledge_point
    if !knowledge_points.empty?
      knowledge_points.each do |kp|
        if kp.knowledge_point_id != knowledge_point_id then
          errors.add(:base, 'has child knowledge point linked.')
          return false
        end
      end
      return true
    end
  end
end

app/controllers/knowledge_points_controller.rb
class KnowledgePointsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_knowledge_point, only: [:show, :edit, :update, :destroy]

  # GET /knowledge_points
  # GET /knowledge_points.json
  def index
    @knowledge_points = KnowledgePoint.all
  end

  # GET /knowledge_points/all_children
  def all_children
    parent_id = params[:id]
    Rails.logger.info("Selected parent:" + parent_id)
    if parent_id.present? then
      @all_second_children = KnowledgePoint.all_children(parent_id)
    end

    Rails.logger.info("Found children:  #{@all_second_children.length}")

    respond_to do |format|
      format.html { redirect_to knowledge_points_url, notice: 'Knowledge points were successfully created.' }
      format.json { render json: @all_second_children }
    end

  end

  # GET /knowledge_points/1
  # GET /knowledge_points/1.json
  def show
  end

  # GET /knowledge_points/new
  def new
    @knowledge_point = KnowledgePoint.new
    @all_children = KnowledgePoint.all_children(-1)
    @all_second_children = []

  end

  # GET /knowledge_points/1/edit
  def edit
  end

  # POST /knowledge_points
  # POST /knowledge_points.json
  def create
    @knowledge_point = KnowledgePoint.new(knowledge_point_params)

    if @knowledge_point.thirdLevelKPSet.present? then
      Rails.logger.info("thirdLevelParent: #{@knowledge_point.thirdLevelParent}")

      parent_kp = KnowledgePoint.find(@knowledge_point.thirdLevelParent)
      create_knowledge_point(@knowledge_point.thirdLevelKPSet, 3, parent_kp.id, parent_kp.name)

    elsif @knowledge_point.secondLevelKPSet.present? then
      Rails.logger.info("secondLevelParent: #{@knowledge_point.secondLevelParent}")

      parent_kp = KnowledgePoint.find(@knowledge_point.secondLevelParent)
      create_knowledge_point(@knowledge_point.secondLevelKPSet, 2, parent_kp.id, parent_kp.name)

    elsif @knowledge_point.firstLevelKPSet.present? then
      Rails.logger.info("firstLevelKPSet: #{@knowledge_point.firstLevelKPSet}")
      create_knowledge_point(@knowledge_point.firstLevelKPSet, 1)

    else

    end

    respond_to do |format|
      format.html { redirect_to knowledge_points_url, notice: 'Knowledge points were successfully created.' }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /knowledge_points/1
  # PATCH/PUT /knowledge_points/1.json
  def update
    respond_to do |format|
      if @knowledge_point.update(knowledge_point_params)
        format.html { redirect_to @knowledge_point, notice: 'KnowledgePoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge_point }
      else
        format.html { render :edit }
        format.json { render json: @knowledge_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledge_points/1
  # DELETE /knowledge_points/1.json
  def destroy
    children = KnowledgePoint.all_children(@knowledge_point.id)
    if children.empty?
      @knowledge_point.destroy
      respond_to do |format|
        format.html { redirect_to knowledge_points_url, notice: 'KnowledgePoint was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to knowledge_points_url, notice: 'KnowledgePoint has children. Cannot be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_knowledge_point
      @knowledge_point = KnowledgePoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def knowledge_point_params
      params.require(:knowledge_point).permit(:name, :firstLevelKP, :firstLevelKPSet,
       :secondLevelParent, :secondLevelKPSet, :thirdLevelGrandParent, :thirdLevelParent, :thirdLevelKPSet)
    end

    def print_knowledge_point (knowledge_point)
      Rails.logger.info("*********")
      Rails.logger.info("name: #{knowledge_point.name}")
      Rails.logger.info("parent_id: #{knowledge_point.parent_id}")
      Rails.logger.info("parent_name: #{knowledge_point.parent_name}")
      Rails.logger.info("memo: #{knowledge_point.memo}")

    end

    def create_knowledge_point(kps, level, parent_id = -1, parent_name = "" )
      Rails.logger.info("****parameters: parent->#{parent_name}, parent_id->#{parent_id}, level->#{level}.")

      kp_array = Array.new()
      if kps.present? then
        names = kps.split(/\r\n/)
        names.each do |name|
          obj = KnowledgePoint.new()
          obj.name = name.strip()
          obj.level = level
          obj.parent_id = parent_id
          obj.parent_name = parent_name
          begin
            obj.save
          rescue => e
            Rails.logger.error("Cannot save #{obj.name}", e)
          end

          Rails.logger.info("Created kp: name->#{obj.name}, parent->#{obj.parent_name}, parent_id->#{obj.parent_id}, level->#{obj.level}.")
          kp_array.push(obj)
        end
      end

      # return kp array
      kp_array
    end
end

app/views/knowledge_points/_form.html.erb
<%= form_for(@knowledge_point) do |f| %>
  <% if @knowledge_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(knowledge_point.errors.count, "error") %> prohibited this knowledge_point from being saved:</h2>

      <ul>
      <% @knowledge_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent%>
    <%= f.text_field :parent_name %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :is_leaf %>
    <%= f.check_box :is_leaf %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/knowledge_points/edit.html.erb
<h1>Editing Knowledge Point</h1>

<!-- <%= render 'form', problem: @problem %> -->

<div class="ad_footerbanner" id="ad_footerbanner3">
<style type="text/css">
#inputWrap{float:left;width:38%}
#inputText{background:#ffffef;width:100%}
#outputWrap{float:right;width:61%}
#output{background:#ffffef;text-align:left;padding:6px;border:solid 1px #ccc;-moz-border-radius:5px;border-radius:5px}
.anniu{font-family:"Tahoma"}
</style>

<div id="inputWrap">
<!-- <textarea id="inputText" rows="15">

</textarea> -->

<%= form_for @knowledge_point, url: {action: "update"} do |f| %>
   <%= f.text_field :name  %>
   <%= f.text_field :parent_name, disabled: true%>
   <%= f.text_field :memo %>
   <%= f.submit "Update" %>
<% end %>


<%= link_to 'Show', @knowledge_point %> |
<%= link_to 'Back', knowledge_points_path %>

app/views/knowledge_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Knowledge Points</h1>

<table>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_description">
      Name
    </td>
    <td class="list_description">
      Parent
    </td>
    <td class="list_description">
      Level
    </td>
    <td class="list_description">
      Action
    </td>
  </tr>
<% @knowledge_points.each do |kp|%>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td class="list_description">
      <dl>
        <dt><%= kp.name %></dt>
      </dl>
    </td>
    <td class="list_description">
      <dl>
        <dt><%= kp.parent_name %></dt>
      </dl>
    </td>
    <td class="list_description">
      <dl>
        <dt><%= kp.level %></dt>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', kp%><br/>
      <%= link_to 'Edit', edit_knowledge_point_path(kp) %><br/>
      <%= link_to 'Destroy', kp, method: :delete,
                   data: { confirm: 'Deleted?' } %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'New Knowledge Point', new_knowledge_point_path %>

app/views/knowledge_points/new.html.erb
<h1>New Knowledge Point</h1>
<div>

</div>

<%= (button_tag "Add First Level", :class =>".addFirstLevel", :style => 'width:180px;font-size:12px', :onclick => 'addFirstLevel()' ) %>
<%= (button_tag "Add Second Level", :class =>".addSecondLevel", :style => 'width:180px;font-size:12px', :onclick => 'addSecondLevel()' ) %>
<%= (button_tag "Add Third Level", :class =>".addThirdLevel", :style => 'width:180px;font-size:12px', :onclick => 'addThirdLevel()' ) %>


<%= form_for @knowledge_point, url: {action: "create"} do |f| %>
  <%= hidden_field_tag "current_action", :id => "current_action" %>
  <br>
  <div id="firstLevel">
  Add First Level
  <br>
  <%= f.text_area  :firstLevelKPSet, id: "firstLevelKPSet", rows: 5, style: "width:30%" %>
  </div>


  <div id="secondLevel">
    Add Second Level
    <br>
    Parent Knowledge Point:
    <%= f.select :secondLevelParent, options_for_select(@all_children.map {|kp| [kp.name, kp.id]}), :prompt => "Please Select" %>
    <br>
    <%= f.text_area :secondLevelKPSet, id: "secondLevelKPSet", rows: 5, style: "width:30%" %>
  </div>

  <div id="thirdLevel">
    Add Third Level
    <br>
    First Level Knowledge Point:
    <%= f.select :thirdLevelGrandParent, options_for_select(@all_children.map {|kp| [kp.name, kp.id]}), :prompt => "Please Select" %>
    <br>
    Second Level Knowledge Point:
    <%= f.select :thirdLevelParent, options_for_select(@all_second_children.map {|kp| [kp.name, kp.id]}), :prompt => "Please Select" %>
    <br>
    <%= f.text_area  :thirdLevelKPSet, id: "thirdLevelKPSet", rows: 5, style: "width:30%" %>
  </div>

  <%= f.submit "Save", id: "save_kp" %>

<% end %>
<%= link_to 'Back', knowledge_points_path %>

<script>
  $(document).on('ready', function() {
    $('#firstLevel').hide();
    $('#secondLevel').hide();
    $('#thirdLevel').hide();

    $('#save_kp').disable
  });

  $('#knowledge_point_thirdLevelGrandParent').on("change", function(){
    var value = $("#knowledge_point_thirdLevelGrandParent option:selected" ).val();
    // alert("changed value:" + value)
    if (value == "") return;

    $.ajax({
        type:'GET',
        dataType:"json",
        url:'/knowledge_points/'+ value + '/all_children' ,

        success:function(data){
          //I assume you want to do something on controller action execution success?
          // alert("data:" + JSON.stringify(data))
          populate_knowledge_point_form(data)
        }
      });
  });

  $('#knowledge_point_thirdLevelParent').on("change", function(){
    //
    // var value = $( "#thirdLevelGrandParent option:selected" ).text();
    // // alert("changed value:" + value)
    // if (value == "") return;
    //
    // var all_children = "#{all_children_knowledge_points_path}?selected_parent_id=" + value;
    // alert("Found children:" + all_children.length)
  });

  function populate_knowledge_point_form(data){
    // var children_kps = JSON.stringify(data)
    $.each(data, function(){
            $("#knowledge_point_thirdLevelParent").append('<option value="'+ this.id +'">'+ this.name +'</option>')
    })
    // for ( var i = 0; i < data.length; i++ ){
    //   alert("child: " + data[i].name)
    //   // $('#dbi_engine_config_' + column).attr('value', dbi_engine[column]);
    // }

  }

  function addFirstLevel() {
    $('#firstLevel').show();
    $('#secondLevel').hide();
    $('#thirdLevel').hide();
    $('#save_kp').enable
    $('#current_action').val("firstLevelAction")

    // alert("current action:" + $('#current_action').val())
  }

  function addSecondLevel() {
    $('#firstLevel').hide();
    $('#secondLevel').show();
    $('#thirdLevel').hide();
    $('#current_action').val("secondLevelAction");
    // alert("current action:" + $('#current_action').val())
  }

  function addThirdLevel() {
    $('#firstLevel').hide();
    $('#secondLevel').hide();
    $('#thirdLevel').show();
    $('#current_action').val("thirdLevelAction")

    // alert("current action:" + $('#current_action').val())
  }
</script>

app/views/knowledge_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @knowledge_point.name %>
</p>

<p>
  <strong>parent:</strong>
  <%= @knowledge_point.parent_name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @knowledge_point.level %>
</p>


<%= link_to 'Edit', edit_knowledge_point_path(@knowledge_point) %> |
<%= link_to 'Back', knowledge_points_path %>


<script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>