config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  resources :problems do
    resources :answers
  end

  # get 'knowledge_points/all_children' => 'knowledge_points#all_children'
  resources :knowledge_points do
    member do
      get :all_children
    end
  end

  resources :tags do
    member do
      get :all_children
      post :new_children
      post :create_children
    end
  end

  devise_for :users
  resources :users

  root to: 'visitors#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  attr_accessor  :tag_indexes, :parent_level

  # before_destroy :ensure_not_referenced_by_any_knowledge_point

  validates :name, :level, presence: true
  validates :name, uniqueness: true

  def self.all_children(parent_id = -1)
     Tag.where("parent_id = ?", parent_id)
  end

  def self.latest
    Tag.order(:updated_at).last
  end

  def normalized_alias_text
    normalized_alias_text = normalized_html(alias_text)
  end


  private

  def normalized_html(alias_text)
    charCodeMap = { 60.chr => "&lt;", 62.chr => "&gt;", 10.chr  => "<br/>", 13.chr => "<br/>"}  #, 60.chr => "&lt;", 62.chr => "&gt;"
    charCodeMap.each do |key, value|
      alias_text = alias_text.gsub(key, value)
      # Rails.logger.debug("******: #{key}->#{value}, #{alias_text}")
    end
    alias_text
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_knowledge_point, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/all_children
  def all_children
    parent_id = params[:id]
    Rails.logger.info("Selected parent:" + parent_id)
    if parent_id.present? then
      @all_second_children = Tag.all_children(parent_id)
    end

    Rails.logger.info("Found children:  #{@all_second_children.length}")

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tags were successfully created.' }
      format.json { render json: @all_second_children }
    end

  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new

  end

  # GET /tags/1/edit
  def edit

  end

  # POST /tags
  # POST /tags.json
  def create
    create_tags(params)

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tags were successfully created.' }
      format.json { head :no_content }
    end
  end

  def create_children

     parent_id = params["tag"]["parent_id"]
     Rails.logger.debug("Parent tag: #{@parent_tag}")

     create_tags(params)

     respond_to do |format|
       format.html { redirect_to tags_url, notice: 'Children tags were successfully created.' }
       format.json { head :no_content }
     end
  end

  def new_children
     tag_id = params["id"]
     @parent_tag = Tag.find(tag_id);
     @tag = Tag.new()

     Rails.logger.debug("Add children tags for #{tag_id}")

  end



  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    Rails.logger.debug("updating...")
    update_sucessful = false
    begin
      update_sucessful = @tag.update(tag_params)
      all_children = Tag.all_children(@tag.id)

      Rails.logger.debug("Found child tags: #{all_children.size} ...")
      all_children.each do |child|
        if child.parent_name != @tag.name
          child.parent_name = @tag.name
          child.save
          Rails.logger.debug("child tag #{child.id} updated...")
        end
      end

    rescue Exception => e
      Rails.logger.error("****Cannot update tag.", e)
    end


    respond_to do |format|
      if update_sucessful
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    children = Tag.all_children(@tag.id)
    if children.empty?
      @tag.destroy
      respond_to do |format|
        format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to tags_url, notice: 'Tag has children. Cannot be destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_knowledge_point
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :alias_text, :memo, :level, :tag_indexes, :parent_id, :parent_name, :parent_level)
    end

    def print_tag (tag)
      Rails.logger.info("*********")
      Rails.logger.info("name: #{tag.name}")
      Rails.logger.info("alias: #{tag.alias_text}")
      Rails.logger.info("parent_id: #{tag.parent_id}")
      Rails.logger.info("parent_name: #{tag.parent_name}")
      Rails.logger.info("memo: #{tag.memo}")

    end

    def create_tags(params)
      tag_indexes = params["tag"]["tag_indexes"]

      if params["tag"]["parent_id"]
        parent_id = params["tag"]["parent_id"].to_i
      else
        parent_id = -1
      end

      parent_name = params["tag"]["parent_name"]
      Rails.logger.debug("parent_name: #{parent_name}")
      if params["tag"]["parent_name"]
        parent_name = params["tag"]["parent_name"]
      else
        parent_name = ""
      end


      Rails.logger.debug("parent_name: #{parent_name}")

      if params["tag"]["parent_level"]
        level = params["tag"]["parent_level"].to_i + 1
      else
        level = 0
      end

      Rails.logger.debug("Parent_id: #{parent_id}, level: #{level}")

      if tag_indexes.strip().length > 0
        indexes = tag_indexes.split(" ")
        indexes.each do |index|
          index = index.strip()
          tag = Tag.new()
          tag.name = params["tag_name_" + index].strip()
          tag.alias_text = params["tag_alias_text_" + index].strip()
          tag.parent_id = parent_id
          tag.parent_name = parent_name
          tag.level = level


          Rails.logger.debug("parent_name: #{parent_name}")

          print_tag(tag)

          tag.save

        end
      end
    end
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :alias %>
    <%= f.text_field :alias %>
  </div>

  <div class="field">
    <%= f.label :memo %>
    <%= f.text_field :memo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_tag_content.html.erb
<div class="tagContentForm">
  <strong> Tag_myvar_</strong>
  <table style="width:100%; table-layout: fixed;">
     <tr>
       <td width="15%"><%= label_tag "Name:"%></td>
       <td ><%= text_field_tag "tag_name_myvar_" %></td>
       <td></td>
     </tr>
     <tr>
       <td width="10%"><%= label_tag "Tag Math Description:"%></td>
       <td width="50%"><%= text_area_tag "tag_alias_text_myvar_", nil, rows: 10, style: "width:100%", id: "tag_alias_text_myvar_"%></td>
       <td width="40%"><div id="tag_alias_output_myvar_"> </div></td>
     </tr>
  </table>

  <%= link_to "X", "#", :onclick => "removeChoice($(this)) && doPreview()", :class => "remove-choice", :id => "X_myvar_" %>
</div>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>


<%= form_for @tag, url: {action: "update"} do |f| %>
  <table style="width:100%; table-layout: fixed;">
      <tr>
        <td width="10%">Parent Name:</td>
        <% if (@tag.parent_name) %>
        <% parent_name_value = @tag.parent_name %>
        <% else %>
        <% parent_name_value = "" %>
        <% end %>
        <td><%= @tag.parent_name %></td>
        <td><%= f.hidden_field :parent_name, :value => parent_name_value %></td>
      </tr>

     <tr>
       <td><%= f.label "Name:"%></td>
       <td><%= f.text_field :name %></td>
       <td></td>
     </tr>
     <tr>
       <td width="10%"><%= f.label "Tag Math Description:"%></td>
       <td width="50%"><%= f.text_area :alias_text, :rows => 10, style: "width:100%", id: "tag_alias_text_1" %></td>
       <td width="40%"><div id="tag_alias_output_1"> </div></td>
     </tr>
     <tr>
       <td><%= f.label "Memo:"%></td>
       <td><%= f.text_field :memo %></td>
       <td></td>
     </tr>
     <tr>
       <td></td>
       <% if (@tag.parent_id) %>
       <% parent_id_value = @tag.parent_id %>
       <% else %>
       <% parent_id_value = -1 %>
       <% end %>
       <td><%= f.hidden_field :parent_id, :value => parent_id_value %></td>
       <td></td>
     </tr>

     <tr>
       <td></td>
       <td><%= f.hidden_field :level %></td>
       <td></td>
     </tr>
  </table>
  <%= f.submit "Update" %>
<% end %>


<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

<script>
  $(document).on("ready", function() {
    $("#tag_alias_text_1").keyup(doPreview);
  });

</script>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_name"> Name  </td>
    <td class="list_description"> Math Description </td>
    <td class="list_normal"> Parent </td>
    <td class="list_normal"> Level </td>
    <td class="list_normal"> Memo </td>
    <td class="list_description"> Action </td>
  </tr>
<% @tags.each do |tag|%>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_name">
        <%= tag.name %>
    </td>
    <td class="list_description">
       <%= tag.normalized_alias_text.html_safe %>
    </td>
    <td class="list_normal">
      <%= tag.parent_name %>
    </td>
    <td class="list_normal">
         <%= tag.level %>
    </td>
    <td class="list_memo">
         <%= tag.memo %>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', tag%><br/>
      <%= link_to 'Edit', edit_tag_path(tag) %><br/>
      <%= link_to 'Add Children', new_children_tag_path(tag.id), :method => :post %><br/>
      <%= link_to 'Destroy', tag, method: :delete,
                   data: { confirm: 'Deleted?' } %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>
<div>

</div>

<%= form_for @tag, url: {action: "create"} do |f| %>
  <%= hidden_field_tag "current_action", :id => "current_action" %>
  <%= f.hidden_field  :tag_indexes, :id => "tag_indexes", :value => " "%>


  <div id="tags">
      <!-- <%= render 'tag_content' %> -->
  </div>

  <a href="javascript:;" id="addNewTag">Add New Tag</a>


  <%= f.submit "Save", id: "save_tag" %>

<% end %>



<%= link_to 'Back', tags_path %>

<div style="display: none;" id="new_tag_content_form">
    <%= render partial: "tag_content", locals: {index: $myvar } %>
</div>


<script>


</script>

app/views/tags/new_children.html.erb
<h1>Parent Tag</h1>
<div class="tagContentField">
  <p>
    <strong>name:</strong>
    <%= @parent_tag.name %>
  </p>

  <p>
    <strong>Math Description:</strong>
    <%= @parent_tag.normalized_alias_text %>
  </p>

  <p>
    <strong>Level:</strong>
    <%= @parent_tag.level %>
  </p>
</div>

<br> <strong>Children Tags:</strong> <br>

<%= form_for @tag, url: {action: "create_children"} do |f| %>
  <%= f.hidden_field :tag_indexes, :id => "tag_indexes", :value => " "%>
  <%= f.hidden_field :parent_id, :value => @parent_tag.id %></td>
  <%= f.hidden_field :parent_level, :value => @parent_tag.level %></td>
  <%= f.hidden_field :parent_name, :value => @parent_tag.name %></td>

  <div id="tags">
      <!-- <%= render 'tag_content' %> -->
  </div>

  <a href="javascript:;" id="addNewTag">Add New Tag</a>


  <%= f.submit "Save", id: "save_tag" %>

<% end %>


<div id="outputWrap"/>



<div id="output">
  <textarea id="outputText" rows="15">
  </textarea>
</div>

<%= link_to 'Back', tags_path %>

<div style="display: none;" id="new_tag_content_form">
    <%= render partial: "tag_content", locals: {index: $myvar } %>
</div>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>parent:</strong>
  <%= @tag.parent_name %>
</p>

<p>
  <strong>name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Math Description:</strong>
  <% if @tag.normalized_alias_text  %>
  <%= @tag.normalized_alias_text.html_safe %>
  <% else %>
  <%= @tag.alias.html_safe %>
  <% end %>
</p>

<p>
  <strong>Level:</strong>
  <%= @tag.level %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>


<script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>